# Variables
@BASE_URL_LOCAL = http://localhost:3333

@user_name = Josuel,
@user_email = josuel@email.com
@user_password = 123teste

### 
## LOCAL
# @name users
POST {{BASE_URL_LOCAL}}/users
Content-Type: application/json

{
  "name": "{{user_name}}",
  "email": "{{user_email}}",
  "password": "{{user_password}}"
}

### 
# @name auth
POST {{BASE_URL_LOCAL}}/sessions/password
Content-Type: application/json

{
  "email": "{{user_email}}",
  "password": "{{user_password}}"
}

### 
# @name user-get
GET {{BASE_URL_LOCAL}}/user/profile
Authorization: Bearer {{auth.response.body.token}}

### 
# @name auth-recover-password
POST {{BASE_URL_LOCAL}}/user/password/recover
Content-Type: application/json

{
  "email": "{{user_email}}"
}

### 
# @name auth-reset-password
POST {{BASE_URL_LOCAL}}/user/password/reset
Content-Type: application/json

{
  "code": "{{auth-recover-password.response.body.result.code}}",
  "password": "new_password_reset"
}