# Variables
@BASE_URL_LOCAL = http://localhost:3333

### 
## LOCAL
# @name users
POST {{BASE_URL_LOCAL}}/users
Content-Type: application/json

{
  "name": "Josuel",
  "email":"josuel@email.com",
  "password": "123teste"
}

### 
# @name auth
POST {{BASE_URL_LOCAL}}/sessions/password
Content-Type: application/json

{
  "email":"josuel@email.com",
  "password": "123teste"
}